theme: jekyll-theme-cayman
title: Mirror mirror on the wall, who's the smartest animal of them all?
description: A quest to analyze all Facebook groups related to Animal Cognition
zip_url: https://example.com/foo.zip
tar_url: https://example.com/foo.tar.gz
